version: "3.9"

services:
  mysql:
    container_name: gotasker-mysql
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: egs
      MYSQL_PASSWORD: eg12
      MYSQL_DATABASE: gotasker
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  app:
    container_name: gotasker-app
    build: .
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      APP_PORT: 4000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: egs
      DB_PASSWORD: eg12
      DB_NAME: gotasker
      JWT_SECRET: SUPERSAFETOKEN_KEY_CHANGE_THIS
